export const countryFlags: Record<string, string> = {
  'Mexico': '🇲🇽',
  'South Africa': '🇿🇦',
  'Korea Republic': '🇰🇷',
  'Czechia': '🇨🇿',
  'Canada': '🇨🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  'United States': '🇺🇸',
  'Paraguay': '🇵🇾',
  'Haiti': '🇭🇹',
  'Scotland': '🇬🇧',
  'Australia': '🇦🇺',
  'Turkiye': '🇹🇷',
  'Brazil': '🇧🇷',
  'Morocco': '🇲🇦',
  'Qatar': '🇶🇦',
  'Switzerland': '🇨🇭',
  'Cote d\'Ivoire': '🇨🇮',
  'Ecuador': '🇪🇨',
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Spain': '🇪🇸',
  'England': '🇬🇧',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Portugal': '🇵🇹',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Denmark': '🇩🇰',
  'Norway': '🇳🇴',
  'Finland': '🇫🇮',
  'Japan': '🇯🇵',
  'China': '🇨🇳',
  'South Korea': '🇰🇷',
  'India': '🇮🇳',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Philippines': '🇵🇭',
  'Russia': '🇷🇺',
  'Ukraine': '🇺🇦',
  'Greece': '🇬🇷',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Serbia': '🇷🇸',
  'Croatia': '🇭🇷',
  'Slovenia': '🇸🇮',
  'Slovakia': '🇸🇰',
  'Austria': '🇦🇹',
  'Switzerland': '🇨🇭',
  'Liechtenstein': '🇱🇮',
  'Turkey': '🇹🇷',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Israel': '🇮🇱',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'Egypt': '🇪🇬',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Kenya': '🇰🇪',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'Senegal': '🇸🇳',
  'Cameroon': '🇨🇲',
  'Angola': '🇦🇴',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Samoa': '🇼🇸',
  'Tonga': '🇹🇴',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Honduras': '🇭🇳',
  'Nicaragua': '🇳🇮',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Belize': '🇧🇿',
  'Peru': '🇵🇪',
  'Colombia': '🇨🇴',
  'Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Bolivia': '🇧🇴',
  'Uruguay': '🇺🇾',
  'Suriname': '🇸🇷',
  'Guyana': '🇬🇾',
  'Luxembourg': '🇱🇺',
  'Malta': '🇲🇹',
  'Cyprus': '🇨🇾',
  'Iceland': '🇮🇸',
  'Ireland': '🇮🇪',
  'Montenegro': '🇲🇪',
  'North Macedonia': '🇲🇰',
  'Kosovo': '🇽🇰',
  'Albania': '🇦🇱',
  'Bulgaria': '🇧🇬',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Turkmenistan': '🇹🇲',
  'Afghanistan': '🇦🇫',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Bhutan': '🇧🇹',
  'Maldives': '🇲🇻',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Hong Kong': '🇭🇰',
  'Taiwan': '🇹🇼',
  'Mongolia': '🇲🇳',
  'Lebanon': '🇱🇧',
  'Jordan': '🇯🇴',
  'Palestine': '🇵🇸',
  'Syria': '🇸🇾',
  'Yemen': '🇾🇪',
  'Oman': '🇴🇲',
  'Kuwait': '🇰🇼',
  'Bahrain': '🇧🇭',
  'Qatar': '🇶🇦',
  'Sudan': '🇸🇩',
  'Ethiopia': '🇪🇹',
  'Somalia': '🇸🇴',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Lesotho': '🇱🇸',
  'Eswatini': '🇸🇿',
  'Madagascar': '🇲🇬',
  'Mauritius': '🇲🇺',
  'Seychelles': '🇸🇨',
};

export function getCountryFlag(countryName: string): string {
  return countryFlags[countryName] || '⚽';
}
